---
abstract: 'Perl extension for DBI to selectively log DBI'
author:
  - 'Martin J. Evans <mjevans@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.6302, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DBIx-LogAny
no_index:
  directory:
    - t
    - inc
requires:
  DBI: 1.5
  Data::Dumper: 0
  File::Spec: 0
  Log::Any: 0.14
  Log::Any::Adapter: 0.1
  Module::Loaded: 0
  Test::More: 0.62
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=DBIx-LogAny
  homepage: http://search.cpan.org/dist/DBIx-LogAny
  repository: https://github.com/mjegh/DBIx-LogAny.git
  x_Mailinglist: http://dbi.perl.org/support
version: 0.04
